backend:
  name: backend
  replicaCount: 1
  image:
    repository: ghcr.io/vizzletf/issuechrono/backend
    tag: 1.0.41
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 3001
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  env:
    - name: NODE_ENV
      value: production
    - name: CORS_ORIGIN
      value: "*"

frontend:
  name: frontend
  replicaCount: 1
  image:
    repository: ghcr.io/vizzletf/issuechrono/frontend
    tag: 1.0.41
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 80
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  env:
    - name: VITE_API_URL
      value: /api

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, PUT, POST, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization"
  hosts:
    - host: gantt.local
      paths:
        - path: /(.*)
          pathType: Prefix
          service: frontend
        - path: /api(/|$)(.*)
          pathType: Prefix
          service: backend
  tls:
    enabled: false
    secretName: ""
    hosts: [] 