backend:
  name: backend
  replicaCount: 1
  image:
    repository: ghcr.io/your-username/gantt-backend
    tag: 1.0.3
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 3001
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  env:
    - name: NODE_ENV
      value: production

frontend:
  name: frontend
  replicaCount: 1
  image:
    repository: ghcr.io/your-username/gantt-frontend
    tag: 1.0.3
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 5173
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  env:
    - name: VITE_API_URL
      value: http://backend:3001

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: gantt.local
      paths:
        - path: /
          pathType: Prefix
          service: frontend
        - path: /api
          pathType: Prefix
          service: backend 