name: Release Helm Chart

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  pages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Package and Push Chart
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Package chart
          helm package chart/

          # Switch to gh-pages branch
          git fetch origin gh-pages || git branch gh-pages
          git checkout gh-pages || git checkout -b gh-pages
          git pull origin gh-pages || true

          # Clean existing files
          git rm -rf . || true
          git clean -fxd

          # Move new files
          mv ../gantt-*.tgz .
          helm repo index . --url https://vizzletf.github.io/IssueChrono
          
          # Commit and push
          git add .
          git commit -m "Release chart ${{ github.ref_name }}"
          git push origin gh-pages 